### ISSUE TITLE
Not getting latest commits in pod update

### ISSUE THREAD

**Issue by helzapps** [PrideChung/FontAwesomeKit#101]
For some reason when I install via pods, `pod 'FontAwesomeKit/Zocial'`, In the `FAKZocial.m` `iconFontWithSize:` method I'm seeing:
```
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self registerIconFontWithURL: [[NSBundle mainBundle] URLForResource:@"zocial-regular-webfont" withExtension:@"ttf"]];
    });
```
But if I clone the repo because I want to create a pull request to fix the line `[[NSBundle mainBundle]]` to `[[NSBundle bundleForClass:[FAKZocial class]]` so it doesn't crash when `use_frameworks!` is in play, I can see that it's already been fixed, and according to the commit history it was changed back in 2015. Why isn't want I'm seeing on the main branch in my cloned repo been made available in the version pulled for pods?

**Comment by RemyDCF** [comment]
As indicated in #79, you can use `pod "FontAwesomeKit", :git => 'https://github.com/PrideChung/FontAwesomeKit.git'` in your Podfile for using latest commits.

**Comment by helzapps** [comment]
Thank you for the response and working fix.
However, If an accepted working fix has been implemented and in use for over a year, as many other commenters on that issue have pointed out, why has that tag not been pushed so that the standard pod update grabs a fix that works with Swift projects?

**Comment by RemyDCF** [comment]
This is a good question...
