### ISSUE TITLE
icon by name

### ISSUE THREAD

**Issue by garyfoster** [PrideChung/FontAwesomeKit#37]
Is it possible to get an icon by name as a string? Something like [FAIcon iconWithName:(NSString *)name size:(CGFloat)size.

I tried calling the the method by reflection using performSelector on FAKFontAwesome but was not able to succeed. I can probably push through this but figured I would ask if there is an easier way.

**Comment by PrideChung** [comment]
Currently there's no easy way to do that. You can call +[FAKFontAwesome allIcons] to get an dictionary of all icons. But the key of this dictionary is the unicode of the icon and the value is the name of the icon. You can swap the key and the value. Then use the name to get the unicode of the icon and call +[FAKFontAwesome iconWithCode:size] to create an icon.

**Comment by garyfoster** [comment]
That's easy actually, I did not realize that allIcons method exists. Might not be the most efficient but works fine for my use, thanks. Here is the snippet in case anyone needs this:

```
    NSString *iconName = @"globe";
    
    NSMutableDictionary *allIcons = [NSMutableDictionary dictionaryWithDictionary:[FAKFontAwesome allIcons]];
    
    for (NSString *key in [allIcons allKeys]) {
        allIcons[allIcons[key]] = key;
        [allIcons removeObjectForKey:key];
    }
    
    NSString *resultCode = [allIcons objectForKey:iconName];
    FAKFontAwesome *icon = [FAKFontAwesome iconWithCode:resultCode size:TAB_ICON_SIZE];
```

**Comment by keyboardsamurai** [comment]
This is a really risky way of doing things. allIcons has loads of duplicate unicode characters. Inverting the dictionary will overwrite some of the keys you may want to look up. A little experimenting yields the following *70* characters that have duplicates: barChartO, btc, car, euro, filePhotoO, filePictureO, fileSoundO, fileVideoO, fileZipO, filesO, flash, ge, gear, gears, institution, jpy, legal, lifeBuoy, lifeRing, lifeSaver, link, mobilePhone, mortarBoard, navicon, outdent, paste, pencilSquareO, photo, pictureO, rebel, remove, reorder, reply, replyAll, rmb, rotateRight, rub, ruble, rupee, save, scissors, send, sendO, share, shekel, sheqel, soccerBallO, sortDown, sortUp, starHalfFull, starHalfO, support, tachometer, taxi, times, toggleDown, toggleLeft, toggleRight, toggleUp, turkishLira, undo, university, unlink, unsorted, usd, users, warning, weixin, won, yen

**Comment by dickyj** [comment]
I used this and it works:
 let FAIconObj = FAKFontAwesome.perform(NSSelectorFromString("\(name)IconWithSize:"), with: iconSize)
