### ISSUE TITLE
Icons looks blurry on iPhone 6 & 6 Plus

### ISSUE THREAD

**Issue by pontus-andersson** [PrideChung/FontAwesomeKit#41]
When converting a FAKIcon to an UIImage (example below), the image looks sharp on iPhone 5S (@2x) but on iPhone 6 Plus it's a bit blurry. 

iPhone 5S
![fakicon_issue2](https://cloud.githubusercontent.com/assets/4217874/7179438/1ddce400-e438-11e4-9400-f5e7a9bee396.jpg)

iPhone 6 Plus
![fakicon_issue](https://cloud.githubusercontent.com/assets/4217874/7179387/9e41d458-e437-11e4-841d-be790e55e979.jpg)

`FAKIcon *filterIcon = [FAKIonIcons iosSettingsStrongIconWithSize:22.0];`
`[filterIcon addAttribute:NSForegroundColorAttributeName value:WHITE_COLOR];`
`UIImage *filterImage = [filterIcon imageWithSize:CGSizeMake(filterIcon.iconFontSize, filterIcon.iconFontSize)];`
`UIBarButtonItem *filterItem = [[UIBarButtonItem alloc] initWithImage:filterImage style:UIBarButtonItemStylePlain target:self action:@selector(showFilterMenu)];`
`self.navigationItem.rightBarButtonItem = filterItem;`

**Comment by parse** [comment]
Same for me. Any ideas?

**Comment by pontus-andersson** [comment]
The problem was related to FontAwesomeKit. It was because the project did not have native resolution for the app on iPhone 6 and 6 Plus.
